import type { Exercise } from "@/lib/exercises";
import { createPullExerciseWithGamification } from "@/lib/exercises/variations/pull/utils/gamificationUtils";
import { PULL_ACHIEVEMENTS } from "@/lib/exercises/variations/pull/data/pullGameData";

// ====================
// EXERCÍCIOS DE PULL - NÍVEL INTERMEDIATE
// ====================

export const intermediatePull: Record<number, Exercise> = {
  9: createPullExerciseWithGamification(
    {
      id: "pull_up",
      name: "Pull-up (Barra Fixa Pronada)",
      muscleGroup: "back",
      difficulty: "intermediate",
      sets: 4,
      reps: "8-12",
      rest: "90s",
      instructions:
        "Segure a barra com pegada pronada (palmas para longe). Puxe o corpo para cima até o queixo passar a barra, depois desça controladamente.",
      tips: "Mantenha o corpo reto, cotovelos apontando para baixo. Não balanceie o corpo. Esta é a barra clássica.",
      equipment: ["Barra"],
      calories: 15,
      xpReward: 25,
      estimatedTime: 420,
      rarity: "common",
      category: "vertical",
      emoji: "💪",
    },
    9,
    25,
    420,
    [
      {
        type: "sets",
        exerciseType: "pullup",
        value: 800,
        description: "Complete 800 séries de exercícios básicos",
      },
    ],
    [PULL_ACHIEVEMENTS[2]!], // pull_master
    "intermediate",
  ),

  10: createPullExerciseWithGamification(
    {
      id: "chin_up",
      name: "Chin-up (Barra de Queixo)",
      muscleGroup: "back",
      difficulty: "intermediate",
      sets: 4,
      reps: "7-10",
      rest: "90s",
      instructions:
        "Use pegada supinada (palmas viradas para você). Puxe o corpo para cima até o queixo passar a barra. Os bíceps são mais recrutados nesta variação.",
      tips: "Cotovelos apontam para frente. Ótimo para desenvolvimento de bíceps junto com dorsais.",
      equipment: ["Barra"],
      calories: 16,
      xpReward: 28,
      estimatedTime: 420,
      rarity: "common",
      category: "vertical",
      emoji: "🤏",
    },
    10,
    28,
    420,
    [
      {
        type: "sets",
        exerciseType: "pullup",
        value: 1000,
        description: "Complete 1000 séries de pull-ups básicos",
      },
    ],
    undefined,
    "intermediate",
  ),

  11: createPullExerciseWithGamification(
    {
      id: "neutral_grip_pull_up",
      name: "Neutral Grip Pull-up",
      muscleGroup: "back",
      difficulty: "intermediate",
      sets: 4,
      reps: "8-12",
      rest: "90s",
      instructions:
        "Use pegada neutra (palmas uma de frente para a outra). Puxe o corpo para cima. Esta pegada reduz tensão nos ombros e pulsos.",
      tips: "Use barras especiais ou argolas. Ideal para quem sente desconforto nas outras pegadas.",
      equipment: ["Barra neutra", "Argolas"],
      calories: 15,
      xpReward: 25,
      estimatedTime: 420,
      rarity: "rare",
      category: "vertical",
      emoji: "🤝",
    },
    11,
    25,
    420,
    [
      {
        type: "sets",
        exerciseType: "pullup",
        value: 1200,
        description: "Complete 1200 séries de pull-ups",
      },
    ],
    undefined,
    "intermediate",
  ),

  12: createPullExerciseWithGamification(
    {
      id: "wide_pull_up",
      name: "Wide Pull-up (Barra Larga)",
      muscleGroup: "back",
      difficulty: "intermediate",
      sets: 4,
      reps: "6-10",
      rest: "90s",
      instructions:
        "Segure a barra com as mãos mais afastadas que a largura dos ombros. Puxe o corpo para cima focando nas costas.",
      tips: "Foca mais nas costas que nos bíceps. Mantenha os ombros afastados. Desafiante para mobilidade.",
      equipment: ["Barra"],
      calories: 17,
      xpReward: 30,
      estimatedTime: 450,
      rarity: "rare",
      category: "vertical",
      emoji: "📏",
    },
    12,
    30,
    450,
    [
      {
        type: "sets",
        exerciseType: "pullup",
        value: 1400,
        description: "Complete 1400 séries de pull-ups",
      },
    ],
    undefined,
    "intermediate",
  ),

  13: createPullExerciseWithGamification(
    {
      id: "close_grip_pull_up",
      name: "Close Grip Pull-up",
      muscleGroup: "back",
      difficulty: "intermediate",
      sets: 4,
      reps: "8-12",
      rest: "90s",
      instructions:
        "Segure a barra com as mãos próximas (mais estreitas que a largura dos ombros). Foca mais nos bíceps e parte inferior das costas.",
      tips: "Mãos quase se tocando. Aumenta recrutamento de bíceps. Técnica precisa para evitar lesões.",
      equipment: ["Barra"],
      calories: 16,
      xpReward: 28,
      estimatedTime: 420,
      rarity: "rare",
      category: "vertical",
      emoji: "🤏",
    },
    13,
    28,
    420,
    [
      {
        type: "sets",
        exerciseType: "pullup",
        value: 1600,
        description: "Complete 1600 séries de pull-ups",
      },
    ],
    undefined,
    "intermediate",
  ),

  14: createPullExerciseWithGamification(
    {
      id: "pull_up_pause",
      name: "Pull-up com Pausa",
      muscleGroup: "back",
      difficulty: "intermediate",
      sets: 4,
      reps: "6-8",
      rest: "120s",
      instructions:
        "Execute pull-ups normais, mas pause por 2-3 segundos no topo e/ou na posição mais baixa. Aumenta força isométrica.",
      tips: "Pause no topo (chest-to-bar) e/ou no fundo. Excelente para força explosiva e controle.",
      equipment: ["Barra"],
      calories: 18,
      xpReward: 32,
      estimatedTime: 480,
      rarity: "epic",
      category: "isometric",
      emoji: "⏸️",
    },
    14,
    32,
    480,
    [
      {
        type: "sets",
        exerciseType: "pullup",
        value: 1800,
        description: "Complete 1800 séries de pull-ups",
      },
    ],
    undefined,
    "intermediate",
  ),

  15: createPullExerciseWithGamification(
    {
      id: "ring_row",
      name: "Ring Row (Remada em Argolas)",
      muscleGroup: "back",
      difficulty: "intermediate",
      sets: 4,
      reps: "10-15",
      rest: "75s",
      instructions:
        "Pendure argolas em altura baixa. Deite embaixo e puxe o corpo em direção às argolas. As argolas aumentam instabilidade.",
      tips: "Ajuste a altura das argolas para dificuldade. Excelente para força horizontal e estabilização.",
      equipment: ["Argolas"],
      calories: 12,
      xpReward: 22,
      estimatedTime: 360,
      rarity: "common",
      category: "horizontal",
      emoji: "🔗",
    },
    15,
    22,
    360,
    [
      {
        type: "sets",
        exerciseType: "pullup",
        value: 1200,
        description: "Complete 1200 séries de pull-ups",
      },
    ],
    undefined,
    "intermediate",
  ),

  16: createPullExerciseWithGamification(
    {
      id: "ring_pull_up",
      name: "Ring Pull-up (Barra em Argolas)",
      muscleGroup: "back",
      difficulty: "intermediate",
      sets: 4,
      reps: "6-10",
      rest: "90s",
      instructions:
        "Execute pull-ups em argolas. As argolas se movem, aumentando instabilidade e recrutando mais estabilizadores.",
      tips: "Comece com argolas mais altas se necessário. Foca na estabilização junto com força de tração.",
      equipment: ["Argolas"],
      calories: 17,
      xpReward: 30,
      estimatedTime: 450,
      rarity: "epic",
      category: "vertical",
      emoji: "🔗",
    },
    16,
    30,
    450,
    [
      {
        type: "sets",
        exerciseType: "pullup",
        value: 2000,
        description: "Complete 2000 séries de pull-ups",
      },
    ],
    undefined,
    "intermediate",
  ),

  17: createPullExerciseWithGamification(
    {
      id: "chest_to_bar",
      name: "Chest-to-Bar (Peito na Barra)",
      muscleGroup: "back",
      difficulty: "intermediate",
      sets: 4,
      reps: "5-8",
      rest: "120s",
      instructions:
        "Puxe o corpo para cima até o peito tocar a barra. Requer amplitude extra e força explosiva.",
      tips: "Mantenha os cotovelos apontando para baixo. Foca na extensão completa dos ombros.",
      equipment: ["Barra"],
      calories: 19,
      xpReward: 35,
      estimatedTime: 480,
      rarity: "epic",
      category: "vertical",
      emoji: "👕",
    },
    17,
    35,
    480,
    [
      {
        type: "sets",
        exerciseType: "pullup",
        value: 2200,
        description: "Complete 2200 séries de pull-ups",
      },
    ],
    undefined,
    "intermediate",
  ),

  18: createPullExerciseWithGamification(
    {
      id: "commando_pull_up",
      name: "Commando Pull-up",
      muscleGroup: "back",
      difficulty: "intermediate",
      sets: 4,
      reps: "4-6 por lado",
      rest: "120s",
      instructions:
        "Puxe o corpo para um lado até o queixo passar a barra, depois para o outro lado. Movimentos alternados.",
      tips: "Controle o movimento lateral. Excelente para força unilateral e coordenação. Técnica avançada.",
      equipment: ["Barra"],
      calories: 18,
      xpReward: 32,
      estimatedTime: 480,
      rarity: "legendary",
      category: "unilateral",
      emoji: "🎖️",
    },
    18,
    32,
    480,
    [
      {
        type: "sets",
        exerciseType: "pullup",
        value: 2400,
        description: "Complete 2400 séries de pull-ups",
      },
    ],
    undefined,
    "intermediate",
  ),

  19: createPullExerciseWithGamification(
    {
      id: "assisted_archer_pull_up",
      name: "Archer Pull-up Assistido",
      muscleGroup: "back",
      difficulty: "intermediate",
      sets: 4,
      reps: "3-5 por lado",
      rest: "150s",
      instructions:
        "Puxe o corpo para um lado enquanto mantém o braço oposto estendido. Use assistência conforme necessário.",
      tips: "Comece com assistência significativa. Foca na força unilateral. Prepare-se para archer completo.",
      equipment: ["Barra", "Elástico"],
      calories: 16,
      xpReward: 28,
      estimatedTime: 480,
      rarity: "legendary",
      category: "unilateral",
      emoji: "🏹",
    },
    19,
    28,
    480,
    [
      {
        type: "sets",
        exerciseType: "pullup",
        value: 2600,
        description: "Complete 2600 séries de pull-ups",
      },
    ],
    undefined,
    "intermediate",
  ),

  20: createPullExerciseWithGamification(
    {
      id: "l_sit_pull_up",
      name: "L-sit Pull-up (Pernas Baixas)",
      muscleGroup: "back",
      difficulty: "intermediate",
      sets: 4,
      reps: "4-6",
      rest: "150s",
      instructions:
        "Mantenha as pernas em L (paralelas ao chão) durante a execução do pull-up. Pernas não precisam estar totalmente horizontais inicialmente.",
      tips: "Comece com as pernas mais baixas. Aumente gradualmente a altura. Desafia core e força de tração simultaneamente.",
      equipment: ["Barra"],
      calories: 22,
      xpReward: 40,
      estimatedTime: 540,
      rarity: "legendary",
      category: "core-integrated",
      emoji: "🦵",
    },
    20,
    40,
    540,
    [
      {
        type: "sets",
        exerciseType: "pullup",
        value: 2800,
        description: "Complete 2800 séries de pull-ups",
      },
    ],
    undefined,
    "intermediate",
  ),
};
