import type { Exercise } from "./exerciseTypes";

export const cardioExercises: Exercise[] = [
  {
    id: "stationary-march",
    name: "Marcha Estacionária",
    muscleGroup: "cardio",
    difficulty: "beginner",
    sets: 1,
    reps: "5 minutos",
    rest: "30s",
    instructions: "Marche no lugar elevando os joelhos alternadamente.",
    tips: "Mantenha o ritmo constante e respire profundamente.",
    equipment: [],
    calories: 25,
  },
  {
    id: "jumping-jacks",
    name: "Polichinelos",
    muscleGroup: "cardio",
    difficulty: "beginner",
    sets: 3,
    reps: "20",
    rest: "45s",
    instructions:
      "Abra e feche as pernas enquanto move os braços para cima e para baixo.",
    tips: "Mantenha os pés juntos quando fechar as pernas.",
    equipment: [],
    calories: 20,
  },
  {
    id: "burpees",
    name: "Burpees",
    muscleGroup: "cardio",
    difficulty: "intermediate",
    sets: 3,
    reps: "10-12",
    rest: "60s",
    instructions:
      "Do agachamento, chute os pés para trás, faça uma flexão e volte.",
    tips: "Mantenha o ritmo constante e respire profundamente.",
    equipment: [],
    calories: 30,
  },
  {
    id: "mountain-climbers",
    name: "Mountain Climbers",
    muscleGroup: "cardio",
    difficulty: "intermediate",
    sets: 3,
    reps: "30s",
    rest: "45s",
    instructions:
      "Em posição de prancha, alterne trazendo os joelhos ao peito.",
    tips: "Mantenha o core contraído e os quadris baixos.",
    equipment: [],
    calories: 25,
  },
  {
    id: "burpee-box-jump",
    name: "Burpee com Salto na Caixa",
    muscleGroup: "cardio",
    difficulty: "advanced",
    sets: 4,
    reps: "8-10",
    rest: "75s",
    instructions: "Burpee seguido de salto sobre uma superfície elevada.",
    tips: "Aterrisse suavemente e mantenha o ritmo.",
    equipment: [],
    calories: 35,
  },
];
