import type { Exercise } from "./exerciseTypes";

export const chestExercises: Exercise[] = [
  {
    id: "push-up",
    name: "Flexão de Braços",
    muscleGroup: "chest",
    difficulty: "beginner",
    sets: 3,
    reps: "10-15",
    rest: "60s",
    instructions:
      "Do topo da cabeça aos calcanhares, corpo em linha reta. Desça até o peito quase tocar o chão.",
    tips: "Mantenha os cotovelos próximos ao corpo e contraia o core.",
    equipment: [],
    calories: 8,
  },
  {
    id: "push-up-knees",
    name: "Flexão com Joelhos",
    muscleGroup: "chest",
    difficulty: "beginner",
    sets: 3,
    reps: "8-12",
    rest: "60s",
    instructions: "Faça flexões apoiando os joelhos no chão.",
    tips: "Mantenha o corpo em linha reta do topo da cabeça aos joelhos.",
    equipment: [],
    calories: 6,
  },
  {
    id: "diamond-push-up",
    name: "Flexão Diamante",
    muscleGroup: "chest",
    difficulty: "intermediate",
    sets: 3,
    reps: "8-12",
    rest: "75s",
    instructions: "Junte as mãos formando um diamante e faça flexões.",
    tips: "Foca mais nos tríceps também.",
    equipment: [],
    calories: 9,
  },
  {
    id: "decline-push-up",
    name: "Flexão Declinada",
    muscleGroup: "chest",
    difficulty: "intermediate",
    sets: 3,
    reps: "8-12",
    rest: "75s",
    instructions: "Coloque os pés elevados e faça flexões.",
    tips: "Aumenta a carga no peito superior.",
    equipment: [],
    calories: 10,
  },
  {
    id: "muscle-up",
    name: "Muscle Up",
    muscleGroup: "chest",
    difficulty: "advanced",
    sets: 3,
    reps: "3-5",
    rest: "90s",
    instructions: "Da barra baixa, puxe-se para cima passando por cima.",
    tips: "Use ímpeto controlado e força explosiva.",
    equipment: ["Barra"],
    calories: 15,
  },
];
