import type { Exercise } from "./exerciseTypes";

export const coreExercises: Exercise[] = [
  {
    id: "plank",
    name: "Prancha",
    muscleGroup: "core",
    difficulty: "beginner",
    sets: 3,
    reps: "20-30s",
    rest: "45s",
    instructions:
      "Mantenha o corpo reto apoiado nos antebraços e pontas dos pés.",
    tips: "Contraia o core e respire normalmente.",
    equipment: [],
    calories: 5,
  },
  {
    id: "side-plank",
    name: "Prancha Lateral",
    muscleGroup: "core",
    difficulty: "intermediate",
    sets: 3,
    reps: "20-30s por lado",
    rest: "45s",
    instructions: "Apoie-se no antebraço e lateral do pé.",
    tips: "Mantenha o corpo em linha reta e os quadris elevados.",
    equipment: [],
    calories: 6,
  },
  {
    id: "russian-twist",
    name: "Torção Russa",
    muscleGroup: "core",
    difficulty: "intermediate",
    sets: 3,
    reps: "15 por lado",
    rest: "60s",
    instructions: "Sentado, gire o tronco de um lado para o outro.",
    tips: "Mantenha os pés no chão e os joelhos dobrados.",
    equipment: [],
    calories: 7,
  },
  {
    id: "bicycle-crunch",
    name: "Abdominal Bicicleta",
    muscleGroup: "core",
    difficulty: "intermediate",
    sets: 3,
    reps: "15 por lado",
    rest: "60s",
    instructions: "Deitado, leve o cotovelo oposto ao joelho alternadamente.",
    tips: "Mantenha as costas coladas ao chão.",
    equipment: [],
    calories: 8,
  },
];
