import type { Exercise } from "./exerciseTypes";

export const legsExercises: Exercise[] = [
  {
    id: "bodyweight-squat",
    name: "Agachamento Livre",
    muscleGroup: "legs",
    difficulty: "beginner",
    sets: 3,
    reps: "12-15",
    rest: "60s",
    instructions: "Desça até os glúteos ficarem abaixo dos joelhos.",
    tips: "Mantenha os pés afastados e os joelhos alinhados com os pés.",
    equipment: [],
    calories: 8,
  },
  {
    id: "wall-sit",
    name: "Agachamento na Parede",
    muscleGroup: "legs",
    difficulty: "beginner",
    sets: 3,
    reps: "20-30s",
    rest: "60s",
    instructions:
      "Deslize pela parede até formar um ângulo de 90° com os joelhos.",
    tips: "Mantenha as costas retas e os pés afastados na largura dos ombros.",
    equipment: [],
    calories: 6,
  },
  {
    id: "lunge",
    name: "Afundo",
    muscleGroup: "legs",
    difficulty: "intermediate",
    sets: 3,
    reps: "10 por perna",
    rest: "75s",
    instructions:
      "Dê um passo à frente e desça até ambos os joelhos formarem 90°.",
    tips: "Mantenha o tronco ereto e o joelho da frente alinhado com o tornozelo.",
    equipment: [],
    calories: 9,
  },
  {
    id: "bulgarian-split-squat",
    name: "Afundo Búlgaro",
    muscleGroup: "legs",
    difficulty: "intermediate",
    sets: 3,
    reps: "8-10 por perna",
    rest: "75s",
    instructions:
      "Coloque um pé atrás em uma superfície elevada e faça agachamentos.",
    tips: "Mantenha o tronco ereto e desça devagar.",
    equipment: [],
    calories: 10,
  },
  {
    id: "pistol-squat",
    name: "Agachamento Pistola",
    muscleGroup: "legs",
    difficulty: "advanced",
    sets: 3,
    reps: "6-8 por perna",
    rest: "90s",
    instructions: "Agachamento unilateral com uma perna estendida.",
    tips: "Mantenha o equilíbrio e desça devagar.",
    equipment: [],
    calories: 12,
  },
];