import type { Exercise } from "@/lib/exercises";
import { createExercise, parseRepRange } from "../../gamificationUtils";
import { EXERCISE_THRESHOLDS } from "../../exerciseData";

export const advancedPushups: Record<number, Exercise> = {
  21: createExercise(
    {
      id: "explosive-push-up",
      name: "Flexão Explosiva",
      muscleGroup: "chest",
      difficulty: "advanced",
      sets: 4,
      reps: parseRepRange("3-6"),
      rest: "150s",
      instructions:
        "Execute flexões com subida explosiva, lançando as mãos do chão.",
      tips: "Requer potência excepcional. Mantenha forma perfeita.",
      equipment: [],
      calories: 20,
      estimatedTime: 1440,
      category: "explosive",
      emoji: "💥",
    },
    21,
    EXERCISE_THRESHOLDS,
    1440,
    [
      {
        type: "sets",
        exerciseType: "pushup",
        value: 6,
        description: "Complete 6 séries de flexão com profundidade",
      },
    ],
    ["Subida explosiva", "Mãos deixam o chão", "Aterrisse suavemente"],
    ["Pratique potência", "Comece sem explosão", "Aumente gradualmente"],
  ),
  22: createExercise(
    {
      id: "pike-push-up",
      name: "Flexão Pike",
      muscleGroup: "chest",
      difficulty: "advanced",
      sets: 4,
      reps: parseRepRange("3-10"),
      rest: "150s",
      instructions:
        "Eleve os quadris formando um V invertido. Desça a cabeça em direção ao chão.",
      tips: "Foca nos ombros. Requer flexibilidade e força.",
      equipment: [],
      calories: 18,
      estimatedTime: 1500,
      category: "shoulder",
      emoji: "🔺",
    },
    22,
    EXERCISE_THRESHOLDS,
    1500,
    [
      {
        type: "sets",
        exerciseType: "pushup",
        value: 6,
        description: "Complete 6 séries de flexão explosiva",
      },
    ],
    ["Corpo em V", "Cabeça ao chão", "Ombros fortes"],
    ["Melhore flexibilidade", "Pratique posição", "Aumente amplitude"],
  ),
  23: createExercise(
    {
      id: "decline-pike-push-up",
      name: "Flexão Pike Declinada",
      muscleGroup: "chest",
      difficulty: "advanced",
      sets: 4,
      reps: parseRepRange("3-6"),
      rest: "180s",
      instructions: "Pike com pés elevados. Aumenta intensidade nos ombros.",
      tips: "Movimento muito avançado. Requer força excepcional.",
      equipment: [],
      calories: 22,
      estimatedTime: 1800,
      category: "shoulder",
      emoji: "📐",
    },
    23,
    EXERCISE_THRESHOLDS,
    1800,
    [
      {
        type: "sets",
        exerciseType: "pushup",
        value: 10,
        description: "Complete 10 séries de flexão pike",
      },
    ],
    ["Pés elevados", "Corpo em V", "Controle total"],
    ["Domine pike primeiro", "Adicione elevação gradual", "Foco na forma"],
  ),
  24: createExercise(
    {
      id: "ring-dips-negative",
      name: "Dips Negativos em Anéis",
      muscleGroup: "chest",
      difficulty: "advanced",
      sets: 3,
      reps: parseRepRange("1-5"),
      rest: "180s",
      instructions: "Em anéis, impulsione para cima e desça lentamente.",
      tips: "Instabilidade extrema. Controle excepcional necessário.",
      equipment: ["anéis"],
      calories: 20,
      estimatedTime: 540,
      category: "stability",
      emoji: "🔄",
    },
    24,
    EXERCISE_THRESHOLDS,
    540,
    [
      {
        type: "sets",
        exerciseType: "pushup",
        value: 6,
        description: "Complete 6 séries de flexão pike declinada",
      },
    ],
    ["Descida controlada", "Anéis instáveis", "Corpo reto"],
    ["Pratique com anéis fixos", "Aumente instabilidade", "Foco no controle"],
  ),
  25: createExercise(
    {
      id: "band-resisted-push-up",
      name: "Flexão com Banda de Resistência",
      muscleGroup: "chest",
      difficulty: "advanced",
      sets: 4,
      reps: parseRepRange("3-8"),
      rest: "150s",
      instructions:
        "Banda elástica sobre as costas. Aumenta resistência na subida.",
      tips: "Adiciona resistência variável. Técnica precisa.",
      equipment: ["banda elástica"],
      calories: 21,
      estimatedTime: 1440,
      category: "strength",
      emoji: "🪢",
    },
    25,
    EXERCISE_THRESHOLDS,
    1440,
    [
      {
        type: "sets",
        exerciseType: "pushup",
        value: 5,
        description: "Complete 5 séries de dips negativos em anéis",
      },
    ],
    ["Banda tensa", "Movimento controlado", "Resistência constante"],
    [
      "Comece com banda leve",
      "Aumente resistência gradualmente",
      "Mantenha forma",
    ],
  ),
  26: createExercise(
    {
      id: "diamond-push-up",
      name: "Flexão Diamante",
      muscleGroup: "chest",
      difficulty: "advanced",
      sets: 4,
      reps: parseRepRange("2-6"),
      rest: "180s",
      instructions: "Mãos juntas formando diamante. Foca tríceps intensamente.",
      tips: "Posição desafiadora. Mantenha cotovelos próximos.",
      equipment: [],
      calories: 19,
      estimatedTime: 1440,
      category: "strength",
      emoji: "💎",
    },
    26,
    EXERCISE_THRESHOLDS,
    1440,
    [
      {
        type: "sets",
        exerciseType: "pushup",
        value: 8,
        description: "Complete 8 séries de flexão com banda",
      },
    ],
    ["Mãos em diamante", "Cotovelos próximos", "Corpo reto"],
    [
      "Comece com mãos próximas",
      "Forme diamante gradualmente",
      "Foco nos tríceps",
    ],
  ),
  27: createExercise(
    {
      id: "depth-explosive-push-up",
      name: "Flexão Profunda Explosiva",
      muscleGroup: "chest",
      difficulty: "advanced",
      sets: 4,
      reps: parseRepRange("2-5"),
      rest: "180s",
      instructions: "Combina descida profunda com subida explosiva.",
      tips: "Movimento complexo que requer força e potência máxima.",
      equipment: [],
      calories: 23,
      estimatedTime: 1800,
      category: "explosive",
      emoji: "🌋",
    },
    27,
    EXERCISE_THRESHOLDS,
    1800,
    [
      {
        type: "sets",
        exerciseType: "pushup",
        value: 6,
        description: "Complete 6 séries de flexão diamante",
      },
    ],
    ["Descida profunda", "Subida explosiva", "Controle perfeito"],
    ["Pratique separadamente", "Combine gradualmente", "Foco na técnica"],
  ),
  28: createExercise(
    {
      id: "incline-explosive-push-up",
      name: "Flexão Explosiva Inclinada",
      muscleGroup: "chest",
      difficulty: "advanced",
      sets: 4,
      reps: parseRepRange("2-5"),
      rest: "180s",
      instructions: "Pés elevados, subida explosiva. Aumenta potência.",
      tips: "Combina inclinação com explosão. Desafio máximo.",
      equipment: [],
      calories: 24,
      estimatedTime: 1800,
      category: "explosive",
      emoji: "⬆️",
    },
    28,
    EXERCISE_THRESHOLDS,
    1800,
    [
      {
        type: "sets",
        exerciseType: "pushup",
        value: 5,
        description: "Complete 5 séries de flexão profunda explosiva",
      },
    ],
    ["Pés elevados", "Subida explosiva", "Aterrisse controlado"],
    ["Domine explosiva primeiro", "Adicione inclinação", "Aumente altura"],
  ),
  29: createExercise(
    {
      id: "ring-dips",
      name: "Dips em Anéis",
      muscleGroup: "chest",
      difficulty: "advanced",
      sets: 3,
      reps: parseRepRange("3-8"),
      rest: "180s",
      instructions: "Dips completos em anéis. Instabilidade máxima.",
      tips: "Movimento de elite. Requer controle excepcional.",
      equipment: ["anéis"],
      calories: 22,
      estimatedTime: 720,
      category: "stability",
      emoji: "🎪",
    },
    29,
    EXERCISE_THRESHOLDS,
    720,
    [
      {
        type: "sets",
        exerciseType: "pushup",
        value: 5,
        description: "Complete 5 séries de flexão explosiva inclinada",
      },
    ],
    ["Anéis instáveis", "Corpo reto", "Controle total"],
    ["Domine dips negativos", "Adicione subida", "Foco na estabilidade"],
  ),
  30: createExercise(
    {
      id: "weighted-dips",
      name: "Dips com Peso",
      muscleGroup: "chest",
      difficulty: "advanced",
      sets: 3,
      reps: parseRepRange("3-8"),
      rest: "180s",
      instructions: "Dips com peso extra. Aumenta resistência máxima.",
      tips: "Para força máxima. Mantenha forma perfeita.",
      equipment: ["peso extra"],
      calories: 25,
      estimatedTime: 720,
      category: "strength",
      emoji: "🏋️",
    },
    30,
    EXERCISE_THRESHOLDS,
    720,
    [
      {
        type: "sets",
        exerciseType: "pushup",
        value: 8,
        description: "Complete 8 séries de dips em anéis",
      },
    ],
    ["Peso extra", "Forma perfeita", "Controle total"],
    ["Comece com pouco peso", "Aumente gradualmente", "Mantenha técnica"],
  ),
};
