import type { Exercise } from "@/lib/exercises";
import {
  createExerciseWithGamification,
  parseRepRange,
} from "@/lib/exercises/gamificationUtils";
import { EXERCISE_THRESHOLDS } from "@/lib/exercises/exerciseData";
// Badge data available via gamification utilities when needed

export const beginnerPushups: Record<number, Exercise> = {
  1: createExerciseWithGamification(
    {
      id: "wall-push-up",
      name: "Flexão na Parede",
      muscleGroup: "chest",
      difficulty: "beginner",
      sets: 4,
      reps: parseRepRange("12-20"),
      rest: "60s",
      instructions:
        "Apoie as mãos na parede em altura dos ombros. Dobre os cotovelos para aproximar o peito da parede, depois estenda os braços.",
      tips: "Mantenha o corpo reto e os cotovelos próximos ao corpo.",
      equipment: [],
      calories: 4,
      xpReward: 5,
      estimatedTime: 180,
      badgeId: "first-pushup",
      rarity: "common",
      category: "strength",
      emoji: "🧱",
    },
    1,
    EXERCISE_THRESHOLDS,
    5,
    180,
    undefined,
    undefined,
    [
      "Mantenha os cotovelos a 45° do corpo",
      "Não arqueie as costas",
      "Desça até o peito tocar a parede",
    ],
    ["Pratique diariamente", "Aumente reps gradualmente", "Foco na forma"]
  ),
  2: createExerciseWithGamification(
    {
      id: "incline-push-up",
      name: "Flexão Inclinada",
      muscleGroup: "chest",
      difficulty: "beginner",
      sets: 4,
      reps: parseRepRange("10-18"),
      rest: "60s",
      instructions:
        "Apoie as mãos em um banco ou superfície elevada. Mantenha o corpo em linha reta e desça até o peito quase tocar a superfície.",
      tips: "Reduz a carga no peito superior. Use uma superfície baixa inicialmente.",
      equipment: ["banco"],
      calories: 5,
      xpReward: 8,
      estimatedTime: 240,
      formTips: [
        "Mantenha o corpo reto",
        "Cotovelos próximos ao corpo",
        "Desça controladamente",
      ],
      progressionTips: [
        "Comece com superfície alta",
        "Abaixe gradualmente",
        "Transicione para flexões no chão",
      ],
      unlocksAt: 20,
      category: "strength",
      emoji: "📈",
    },
    2,
    EXERCISE_THRESHOLDS,
    8,
    240,
    [
      {
        type: "sets",
        exerciseType: "pushup",
        value: 20,
        description: "Complete 20 séries de flexão na parede",
      },
    ],
    undefined,
    ["Corpo em linha reta", "Cotovelos a 45°", "Amplitude completa"],
    ["Use superfície elevada", "Abaixe gradualmente", "Foco na forma"]
  ),
  3: createExerciseWithGamification(
    {
      id: "knee-push-up",
      name: "Flexão com Joelhos",
      muscleGroup: "chest",
      difficulty: "beginner",
      sets: 4,
      reps: parseRepRange("8-15"),
      rest: "60s",
      instructions:
        "Apoie os joelhos no chão. Mantenha o corpo em linha reta do topo da cabeça aos joelhos. Desça até o peito quase tocar o chão.",
      tips: "Mantenha o core contraído e os cotovelos próximos ao corpo.",
      equipment: [],
      calories: 6,
      xpReward: 10,
      estimatedTime: 300,
      formTips: [
        "Corpo reto dos joelhos à cabeça",
        "Cotovelos próximos ao corpo",
        "Não deixe os quadris caírem",
      ],
      progressionTips: [
        "Comece devagar",
        "Aumente reps gradualmente",
        "Transicione para flexões completas",
      ],
      unlocksAt: 18,
      category: "strength",
      emoji: "🦵",
    },
    3,
    EXERCISE_THRESHOLDS,
    12,
    300,
    [
      {
        type: "sets",
        exerciseType: "pushup",
        value: 18,
        description: "Complete 18 séries de flexão inclinada",
      },
    ],
    undefined,
    ["Corpo em linha reta", "Core contraído", "Cotovelos próximos"],
    [
      "Pratique forma perfeita",
      "Aumente reps lentamente",
      "Prepare para flexões completas",
    ]
  ),
  4: createExerciseWithGamification(
    {
      id: "push-up",
      name: "Flexão Padrão",
      muscleGroup: "chest",
      difficulty: "beginner",
      sets: 4,
      reps: parseRepRange("6-15"),
      rest: "60s",
      instructions:
        "Do topo da cabeça aos calcanhares, corpo em linha reta. Desça até o peito quase tocar o chão.",
      tips: "Mantenha os cotovelos próximos ao corpo e contraia o core.",
      equipment: [],
      calories: 8,
      xpReward: 12,
      estimatedTime: 360,
      formTips: ["Corpo em linha reta", "Cotovelos a 45°", "Olhe para frente"],
      progressionTips: [
        "Foco na forma",
        "Aumente reps gradualmente",
        "Experimente variações",
      ],
      unlocksAt: 15,
      category: "strength",
      emoji: "💪",
    },
    4,
    EXERCISE_THRESHOLDS,
    15,
    360,
    [
      {
        type: "sets",
        exerciseType: "pushup",
        value: 15,
        description: "Complete 15 séries de flexão com joelhos",
      },
    ],
    undefined,
    ["Corpo reto", "Core contraído", "Cotovelos próximos"],
    ["Pratique diariamente", "Aumente reps", "Mantenha forma"]
  ),
  5: createExerciseWithGamification(
    {
      id: "wide-push-up",
      name: "Flexão Larga",
      muscleGroup: "chest",
      difficulty: "beginner",
      sets: 4,
      reps: parseRepRange("6-12"),
      rest: "75s",
      instructions:
        "Mãos afastadas além da largura dos ombros. Desça até o peito tocar o chão.",
      tips: "Foca mais no peito. Mantenha os cotovelos abertos.",
      equipment: [],
      calories: 9,
      xpReward: 15,
      estimatedTime: 420,
      formTips: [
        "Mãos mais afastadas",
        "Cotovelos abertos",
        "Amplitude completa",
      ],
      progressionTips: [
        "Comece com afastamento moderado",
        "Aumente gradualmente",
        "Foco no peito",
      ],
      unlocksAt: 12,
      category: "strength",
      emoji: "👐",
    },
    5,
    EXERCISE_THRESHOLDS,
    18,
    420,
    [
      {
        type: "sets",
        exerciseType: "pushup",
        value: 12,
        description: "Complete 12 séries de flexão padrão",
      },
    ],
    undefined,
    ["Mãos afastadas", "Cotovelos abertos", "Corpo reto"],
    ["Aumente afastamento gradualmente", "Foco no peito", "Mantenha forma"]
  ),
  6: createExerciseWithGamification(
    {
      id: "close-push-up",
      name: "Flexão Estreita",
      muscleGroup: "chest",
      difficulty: "beginner",
      sets: 4,
      reps: parseRepRange("6-12"),
      rest: "75s",
      instructions:
        "Mãos juntas formando um diamante sob o peito. Desça até o peito tocar nas mãos.",
      tips: "Foca nos tríceps. Mantenha os cotovelos próximos ao corpo.",
      equipment: [],
      calories: 10,
      xpReward: 18,
      estimatedTime: 480,
      formTips: ["Mãos juntas", "Cotovelos próximos", "Corpo reto"],
      progressionTips: [
        "Comece com mãos próximas",
        "Aproxime gradualmente",
        "Foco nos tríceps",
      ],
      unlocksAt: 12,
      category: "strength",
      emoji: "🤏",
    },
    6,
    EXERCISE_THRESHOLDS,
    20,
    480,
    [
      {
        type: "sets",
        exerciseType: "pushup",
        value: 12,
        description: "Complete 12 séries de flexão larga",
      },
    ],
    undefined,
    ["Mãos juntas", "Cotovelos colados", "Amplitude completa"],
    ["Pratique forma", "Aumente reps", "Prepare para diamante"]
  ),
  7: createExerciseWithGamification(
    {
      id: "elbows-in-push-up",
      name: "Flexão Cotovelos para Dentro",
      muscleGroup: "chest",
      difficulty: "beginner",
      sets: 4,
      reps: parseRepRange("6-10"),
      rest: "75s",
      instructions:
        "Durante a descida, traga os cotovelos para dentro do corpo. Suba com cotovelos abertos.",
      tips: "Melhora controle e força lateral. Técnica avançada para iniciante.",
      equipment: [],
      calories: 11,
      xpReward: 20,
      estimatedTime: 540,
      formTips: [
        "Cotovelos para dentro na descida",
        "Para fora na subida",
        "Corpo reto",
      ],
      progressionTips: [
        "Pratique movimento lento",
        "Foco no controle",
        "Aumente reps",
      ],
      unlocksAt: 10,
      category: "control",
      emoji: "🦾",
    },
    7,
    EXERCISE_THRESHOLDS,
    22,
    540,
    [
      {
        type: "sets",
        exerciseType: "pushup",
        value: 10,
        description: "Complete 10 séries de flexão estreita",
      },
    ],
    undefined,
    ["Cotovelos para dentro", "Controle o movimento", "Corpo estável"],
    ["Pratique devagar", "Foco na técnica", "Aumente controle"]
  ),
  8: createExerciseWithGamification(
    {
      id: "shoulder-tap-push-up",
      name: "Flexão com Toque no Ombro",
      muscleGroup: "chest",
      difficulty: "intermediate",
      sets: 4,
      reps: parseRepRange("5-10"),
      rest: "90s",
      instructions:
        "No topo, toque o ombro oposto com a mão. Alterne os lados.",
      tips: "Desafia equilíbrio e core. Mantenha o corpo estável.",
      equipment: [],
      calories: 12,
      xpReward: 25,
      estimatedTime: 600,
      formTips: [
        "Corpo completamente reto",
        "Toque o ombro oposto",
        "Mantenha equilíbrio",
      ],
      progressionTips: [
        "Comece sem tocar",
        "Adicione toque gradual",
        "Foco no equilíbrio",
      ],
      unlocksAt: 10,
      category: "stability",
      emoji: "🤾",
    },
    8,
    EXERCISE_THRESHOLDS,
    25,
    600,
    [
      {
        type: "sets",
        exerciseType: "pushup",
        value: 10,
        description: "Complete 10 séries de flexão cotovelos para dentro",
      },
    ],
    undefined,
    ["Corpo reto", "Toque controlado", "Equilíbrio perfeito"],
    ["Pratique estabilidade", "Comece devagar", "Aumente velocidade"]
  ),
  9: createExerciseWithGamification(
    {
      id: "uneven-push-up",
      name: "Flexão Desigual",
      muscleGroup: "chest",
      difficulty: "intermediate",
      sets: 4,
      reps: parseRepRange("5-8"),
      rest: "90s",
      instructions: "Uma mão elevada, outra no chão. Alterne os lados.",
      tips: "Desafia força unilateral e equilíbrio. Use elevação baixa.",
      equipment: [],
      calories: 13,
      xpReward: 28,
      estimatedTime: 660,
      formTips: ["Mão elevada baixa", "Corpo reto", "Distribua peso"],
      progressionTips: [
        "Use bloco baixo",
        "Aumente altura gradualmente",
        "Foco na força unilateral",
      ],
      unlocksAt: 8,
      category: "strength",
      emoji: "⚖️",
    },
    9,
    EXERCISE_THRESHOLDS,
    28,
    660,
    [
      {
        type: "sets",
        exerciseType: "pushup",
        value: 8,
        description: "Complete 8 séries de flexão com toque no ombro",
      },
    ],
    undefined,
    ["Corpo reto", "Peso distribuído", "Controle total"],
    ["Comece com elevação baixa", "Aumente gradualmente", "Melhore equilíbrio"]
  ),
  10: createExerciseWithGamification(
    {
      id: "bench-dips",
      name: "Dips no Banco",
      muscleGroup: "chest",
      difficulty: "beginner",
      sets: 3,
      reps: parseRepRange("5-12"),
      rest: "90s",
      instructions:
        "Sente na borda do banco, mãos ao lado do corpo. Desça até formar 90° nos cotovelos.",
      tips: "Foca tríceps e peito inferior. Mantenha cotovelos próximos.",
      equipment: ["banco"],
      calories: 8,
      xpReward: 15,
      estimatedTime: 240,
      formTips: ["Cotovelos próximos", "Desça até 90°", "Corpo controlado"],
      progressionTips: [
        "Comece com amplitude parcial",
        "Aumente gradualmente",
        "Foco na forma",
      ],
      unlocksAt: 8,
      category: "strength",
      emoji: "🪑",
    },
    10,
    EXERCISE_THRESHOLDS,
    15,
    240,
    [
      {
        type: "sets",
        exerciseType: "pushup",
        value: 8,
        description: "Complete 8 séries de flexão desigual",
      },
    ],
    undefined,
    ["Cotovelos próximos", "Amplitude controlada", "Corpo reto"],
    ["Pratique forma", "Aumente reps", "Prepare para dips avançados"]
  ),
};
