import type { Exercise } from "@/lib/exercises";
import { createExercise, parseRepRange } from "../../gamificationUtils";
import { EXERCISE_THRESHOLDS } from "../../exerciseData";
// Badge data available via gamification utilities when needed

export const extremePushups: Record<number, Exercise> = {
  31: createExercise(
    {
      id: "1-clap-push-up",
      name: "Flexão com 1 Batida",
      muscleGroup: "chest",
      difficulty: "extreme",
      sets: 4,
      reps: parseRepRange("1-3"),
      rest: "180s",
      instructions: "Subida explosiva com batida de palmas à frente do peito.",
      tips: "Coordenação e potência máxima. Técnica perfeita necessária.",
      equipment: [],
      calories: 25,
      // xpReward removed
      estimatedTime: 1800,
      category: "explosive",
      emoji: "👏",
    },
    31,
    EXERCISE_THRESHOLDS,
    1800,
    [
      {
        type: "sets",
        exerciseType: "pushup",
        value: 8,
        description: "Complete 8 séries de dips com peso",
      },
    ],
    ["Subida explosiva", "Batida de palmas", "Aterrisse controlado"],
    ["Pratique sem batida", "Adicione batida gradual", "Foco na coordenação"],
  ),
  32: createExercise(
    {
      id: "clap-chest-push-up",
      name: "Flexão Batida no Peito",
      muscleGroup: "chest",
      difficulty: "extreme",
      sets: 4,
      reps: parseRepRange("1-3"),
      rest: "180s",
      instructions: "Batida de palmas no nível do peito durante subida.",
      tips: "Movimento complexo. Requer timing perfeito.",
      equipment: [],
      calories: 26,
      // xpReward removed
      estimatedTime: 1800,
      category: "explosive",
      emoji: "🤛",
    },
    32,
    EXERCISE_THRESHOLDS,
    1800,
    [
      {
        type: "sets",
        exerciseType: "pushup",
        value: 3,
        description: "Complete 3 séries de flexão com 1 batida",
      },
    ],
    ["Batida no peito", "Timing perfeito", "Controle de voo"],
    ["Domine 1 batida", "Ajuste altura da batida", "Pratique coordenação"],
  ),
  33: createExercise(
    {
      id: "clap-thigh-push-up",
      name: "Flexão Batida na Coxa",
      muscleGroup: "chest",
      difficulty: "extreme",
      sets: 4,
      reps: parseRepRange("1-2"),
      rest: "180s",
      instructions: "Batida de palmas nas coxas durante subida.",
      tips: "Movimento acrobático. Força e flexibilidade máxima.",
      equipment: [],
      calories: 27,
      // xpReward removed
      estimatedTime: 1800,
      category: "explosive",
      emoji: "🦵",
    },
    33,
    EXERCISE_THRESHOLDS,
    1800,
    [
      {
        type: "sets",
        exerciseType: "pushup",
        value: 3,
        description: "Complete 3 séries de flexão batida no peito",
      },
    ],
    ["Batida nas coxas", "Corpo compacto", "Aterrisse preciso"],
    ["Pratique flexibilidade", "Ajuste posição", "Foco na precisão"],
  ),
  34: createExercise(
    {
      id: "clap-behind-back-push-up",
      name: "Flexão Batida Atrás das Costas",
      muscleGroup: "chest",
      difficulty: "extreme",
      sets: 4,
      reps: parseRepRange("1-2"),
      rest: "180s",
      instructions: "Batida de palmas atrás das costas durante subida.",
      tips: "Movimento de elite. Requer força e coordenação excepcional.",
      equipment: [],
      calories: 28,
      // xpReward removed
      estimatedTime: 1800,
      category: "explosive",
      emoji: "🔙",
    },
    34,
    EXERCISE_THRESHOLDS,
    1800,
    [
      {
        type: "sets",
        exerciseType: "pushup",
        value: 2,
        description: "Complete 2 séries de flexão batida na coxa",
      },
    ],
    ["Batida atrás", "Rotação controlada", "Aterrisse estável"],
    ["Domine batidas anteriores", "Pratique rotação", "Foco na segurança"],
  ),
  35: createExercise(
    {
      id: "bear-crawl-push-up",
      name: "Flexão Andar do Urso",
      muscleGroup: "chest",
      difficulty: "extreme",
      sets: 4,
      reps: parseRepRange("1-6"),
      rest: "180s",
      instructions: "No topo, ande 1 passo para frente antes de descer.",
      tips: "Combina força com coordenação. Movimento complexo.",
      equipment: [],
      calories: 24,
      // xpReward removed
      estimatedTime: 2160,
      category: "coordination",
      emoji: "🐻",
    },
    35,
    EXERCISE_THRESHOLDS,
    2160,
    [
      {
        type: "sets",
        exerciseType: "pushup",
        value: 2,
        description: "Complete 2 séries de flexão batida atrás",
      },
    ],
    ["Ande no topo", "Corpo coordenado", "Ritmo constante"],
    ["Pratique andar separado", "Adicione flexão gradual", "Mantenha ritmo"],
  ),
  36: createExercise(
    {
      id: "double-clap-push-up",
      name: "Flexão com 2 Batidas",
      muscleGroup: "chest",
      difficulty: "extreme",
      sets: 4,
      reps: parseRepRange("1-2"),
      rest: "180s",
      instructions: "Duas batidas de palmas durante subida explosiva.",
      tips: "Potência e coordenação máxima. Movimento de elite.",
      equipment: [],
      calories: 29,
      // xpReward removed
      estimatedTime: 1800,
      category: "explosive",
      emoji: "👏👏",
    },
    36,
    EXERCISE_THRESHOLDS,
    1800,
    [
      {
        type: "sets",
        exerciseType: "pushup",
        value: 6,
        description: "Complete 6 séries de flexão andar do urso",
      },
    ],
    ["Duas batidas", "Ritmo perfeito", "Controle de voo"],
    ["Domine 1 batida", "Adicione segunda batida", "Pratique timing"],
  ),
  37: createExercise(
    {
      id: "archer-push-up",
      name: "Flexão Arqueiro",
      muscleGroup: "chest",
      difficulty: "extreme",
      sets: 4,
      reps: parseRepRange("1-4"),
      rest: "180s",
      instructions: "Estenda um braço lateralmente enquanto desce com o outro.",
      tips: "Força unilateral máxima. Equilíbrio excepcional.",
      equipment: [],
      calories: 26,
      // xpReward removed
      estimatedTime: 2160,
      category: "strength",
      emoji: "🏹",
    },
    37,
    EXERCISE_THRESHOLDS,
    2160,
    [
      {
        type: "sets",
        exerciseType: "pushup",
        value: 2,
        description: "Complete 2 séries de flexão com 2 batidas",
      },
    ],
    ["Braço estendido", "Corpo reto", "Controle lateral"],
    ["Pratique unilateral", "Aumente extensão", "Foco no equilíbrio"],
  ),
  38: createExercise(
    {
      id: "triple-clap-push-up",
      name: "Flexão com 3 Batidas",
      muscleGroup: "chest",
      difficulty: "extreme",
      sets: 4,
      reps: parseRepRange("1"),
      rest: "180s",
      instructions: "Três batidas de palmas durante subida. Movimento máximo.",
      tips: "Potência, coordenação e força de elite absoluta.",
      equipment: [],
      calories: 30,
      // xpReward removed
      estimatedTime: 1800,
      category: "explosive",
      emoji: "👏👏👏",
    },
    38,
    EXERCISE_THRESHOLDS,
    1800,
    [
      {
        type: "sets",
        exerciseType: "pushup",
        value: 4,
        description: "Complete 4 séries de flexão arqueiro",
      },
    ],
    ["Três batidas", "Ritmo impecável", "Controle absoluto"],
    ["Domine 2 batidas", "Adicione terceira", "Foco na perfeição"],
  ),
  39: createExercise(
    {
      id: "rotating-180-push-up",
      name: "Flexão Rotação 180°",
      muscleGroup: "chest",
      difficulty: "extreme",
      sets: 4,
      reps: parseRepRange("1"),
      rest: "180s",
      instructions: "Rotação completa do corpo durante subida explosiva.",
      tips: "Movimento acrobático de nível mundial.",
      equipment: [],
      calories: 32,
      // xpReward removed
      estimatedTime: 1800,
      category: "coordination",
      emoji: "🔄",
    },
    39,
    EXERCISE_THRESHOLDS,
    1800,
    [
      {
        type: "sets",
        exerciseType: "pushup",
        value: 1,
        description: "Complete 1 série de flexão com 3 batidas",
      },
    ],
    ["Rotação 180°", "Controle de voo", "Aterrisse preciso"],
    ["Pratique rotação", "Adicione explosão", "Foco na segurança"],
  ),
  40: createExercise(
    {
      id: "fingertip-push-up",
      name: "Flexão na Ponta dos Dedos",
      muscleGroup: "chest",
      difficulty: "extreme",
      sets: 4,
      reps: parseRepRange("1-5"),
      rest: "180s",
      instructions: "Apoio apenas na ponta dos dedos. Força máxima.",
      tips: "Desafia força dos dedos e pulsos. Técnica avançada.",
      equipment: [],
      calories: 28,
      // xpReward removed
      estimatedTime: 1800,
      category: "strength",
      emoji: "👆",
    },
    40,
    EXERCISE_THRESHOLDS,
    1800,
    [
      {
        type: "sets",
        exerciseType: "pushup",
        value: 1,
        description: "Complete 1 série de flexão rotação 180°",
      },
    ],
    ["Ponta dos dedos", "Pulsos retos", "Distribua peso"],
    ["Fortaleça dedos", "Comece com apoio parcial", "Aumente gradualmente"],
  ),
  41: createExercise(
    {
      id: "towel-slide-push-up",
      name: "Flexão Deslizar Toalha",
      muscleGroup: "chest",
      difficulty: "extreme",
      sets: 4,
      reps: parseRepRange("1-6"),
      rest: "180s",
      instructions: "Mãos em toalhas que deslizam. Instabilidade máxima.",
      tips: "Coordenação e controle excepcional necessário.",
      equipment: ["toalhas"],
      calories: 27,
      // xpReward removed
      estimatedTime: 2160,
      category: "stability",
      emoji: "🧽",
    },
    41,
    EXERCISE_THRESHOLDS,
    2160,
    [
      {
        type: "sets",
        exerciseType: "pushup",
        value: 5,
        description: "Complete 5 séries de flexão na ponta dos dedos",
      },
    ],
    ["Toalhas deslizam", "Controle constante", "Adapte posição"],
    ["Pratique deslizar", "Adicione flexão", "Foco na estabilidade"],
  ),
  42: createExercise(
    {
      id: "tuck-planche-push-up",
      name: "Flexão Tuck Planche",
      muscleGroup: "chest",
      difficulty: "extreme",
      sets: 4,
      reps: parseRepRange("1-5"),
      rest: "180s",
      instructions: "Joelhos junto ao peito em posição de planche.",
      tips: "Força de planche completa. Movimento de elite.",
      equipment: [],
      calories: 31,
      // xpReward removed
      estimatedTime: 1800,
      category: "core",
      emoji: "🧘",
    },
    42,
    EXERCISE_THRESHOLDS,
    1800,
    [
      {
        type: "sets",
        exerciseType: "pushup",
        value: 6,
        description: "Complete 6 séries de flexão deslizar toalha",
      },
    ],
    ["Joelhos no peito", "Corpo paralelo", "Core máximo"],
    ["Domine tuck planche", "Adicione movimento", "Construa força"],
  ),
  43: createExercise(
    {
      id: "planche-hold",
      name: "Sustentação Planche",
      muscleGroup: "chest",
      difficulty: "extreme",
      sets: 4,
      reps: parseRepRange("10-20"),
      rest: "180s",
      instructions: "Sustente posição de planche completa por segundos.",
      tips: "Força isométrica máxima. Base para planche push-up.",
      equipment: [],
      calories: 15,
      // xpReward removed
      estimatedTime: 1200,
      category: "core",
      emoji: "⏱️",
    },
    43,
    EXERCISE_THRESHOLDS,
    1200,
    [
      {
        type: "sets",
        exerciseType: "pushup",
        value: 5,
        description: "Complete 5 séries de flexão tuck planche",
      },
    ],
    ["Corpo paralelo", "Braços retos", "Core contraído"],
    ["Pratique holds curtos", "Aumente tempo gradualmente", "Foco na forma"],
  ),
  44: createExercise(
    {
      id: "full-planche-push-up",
      name: "Flexão Planche Completa",
      muscleGroup: "chest",
      difficulty: "extreme",
      sets: 4,
      reps: parseRepRange("1-3"),
      rest: "180s",
      instructions: "Flexão completa na posição de planche. Movimento máximo.",
      tips: "Força total do corpo. Cume da calistenia.",
      equipment: [],
      calories: 35,
      // xpReward removed
      estimatedTime: 1800,
      category: "core",
      emoji: "👑",
    },
    44,
    EXERCISE_THRESHOLDS,
    1800,
    [
      {
        type: "sets",
        exerciseType: "pushup",
        value: 20,
        description: "Complete 20 segundos de planche hold",
      },
    ],
    ["Corpo paralelo", "Movimento controlado", "Força máxima"],
    [
      "Domine tudo anterior",
      "Construa força gradualmente",
      "Foco na perfeição",
    ],
  ),
};
