import type { Exercise } from "@/lib/exercises";
import {
  createExerciseWithGamification,
  parseRepRange,
} from "@/lib/exercises/gamificationUtils";
import { EXERCISE_THRESHOLDS } from "@/lib/exercises/exerciseData";

export const intermediatePushups: Record<number, Exercise> = {
  11: createExerciseWithGamification(
    {
      id: "decline-push-up",
      name: "Flexão Declinada",
      muscleGroup: "chest",
      difficulty: "intermediate",
      sets: 4,
      reps: parseRepRange("5-12"),
      rest: "90s",
      instructions:
        "Coloque os pés elevados (em uma cadeira ou step). Mantenha o corpo em linha reta e desça até o peito quase tocar o chão.",
      tips: "Aumenta a carga no peito superior. Mantenha o core contraído.",
      equipment: [],
      calories: 12,
      xpReward: 30,
      estimatedTime: 720,
      category: "strength",
      emoji: "📈",
    },
    11,
    EXERCISE_THRESHOLDS,
    30,
    720,
    [
      {
        type: "sets",
        exerciseType: "pushup",
        value: 8,
        description: "Complete 8 séries de dips no banco",
      },
    ],
    undefined,
    [
      "Corpo em linha reta",
      "Não deixe a cabeça cair",
      "Controle a descida e subida",
    ],
    [
      "Use uma superfície baixa inicialmente",
      "Aumente a altura gradualmente",
      "Foco no peito superior",
    ],
  ),
  12: createExerciseWithGamification(
    {
      id: "bosu-push-up",
      name: "Flexão em Superfície Instável",
      muscleGroup: "chest",
      difficulty: "intermediate",
      sets: 4,
      reps: parseRepRange("5-10"),
      rest: "90s",
      instructions:
        "Execute flexões com as mãos em uma superfície instável (Bosu ou similar).",
      tips: "Desafia estabilidade e força. Mantenha o corpo reto.",
      equipment: ["bosu"],
      calories: 13,
      xpReward: 32,
      estimatedTime: 780,
      category: "stability",
      emoji: "🟢",
    },
    12,
    EXERCISE_THRESHOLDS,
    32,
    780,
    [
      {
        type: "sets",
        exerciseType: "pushup",
        value: 12,
        description: "Complete 12 séries de flexão declinada",
      },
    ],
    undefined,
    ["Mantenha estabilidade", "Corpo reto", "Controle o movimento"],
    [
      "Comece com superfície estável",
      "Adicione instabilidade gradualmente",
      "Foco no equilíbrio",
    ],
  ),
  13: createExerciseWithGamification(
    {
      id: "parallel-bar-dips-negative",
      name: "Dips Negativos em Barras",
      muscleGroup: "chest",
      difficulty: "intermediate",
      sets: 3,
      reps: parseRepRange("3-6"),
      rest: "120s",
      instructions:
        "Pule ou impulsione para a posição alta e desça lentamente controlando o movimento.",
      tips: "Enfatize a fase negativa. Controle total da descida.",
      equipment: ["barras paralelas"],
      calories: 14,
      xpReward: 35,
      estimatedTime: 360,
      category: "strength",
      emoji: "📉",
    },
    13,
    EXERCISE_THRESHOLDS,
    35,
    360,
    [
      {
        type: "sets",
        exerciseType: "pushup",
        value: 10,
        description: "Complete 10 séries de flexão em superfície instável",
      },
    ],
    undefined,
    ["Desça lentamente", "Corpo reto", "Controle total"],
    [
      "Pratique descida controlada",
      "Use impulso mínimo",
      "Aumente tempo de descida",
    ],
  ),
  14: createExerciseWithGamification(
    {
      id: "ring-push-up",
      name: "Flexão em Anéis",
      muscleGroup: "chest",
      difficulty: "intermediate",
      sets: 4,
      reps: parseRepRange("3-8"),
      rest: "120s",
      instructions:
        "Execute flexões usando anéis de ginástica. Os anéis aumentam a instabilidade.",
      tips: "Movimento desafiador devido à instabilidade. Requer controle excepcional.",
      equipment: ["anéis"],
      calories: 15,
      xpReward: 38,
      estimatedTime: 960,
      category: "stability",
      emoji: "⭕",
    },
    14,
    EXERCISE_THRESHOLDS,
    38,
    960,
    [
      {
        type: "sets",
        exerciseType: "pushup",
        value: 6,
        description: "Complete 6 séries de dips negativos",
      },
    ],
    undefined,
    [
      "Controle a instabilidade",
      "Mantenha ombros estáveis",
      "Amplitude completa",
    ],
    [
      "Pratique com anéis fixos",
      "Aumente instabilidade gradualmente",
      "Foco na forma",
    ],
  ),
  15: createExerciseWithGamification(
    {
      id: "paused-push-up",
      name: "Flexão Pausada",
      muscleGroup: "chest",
      difficulty: "intermediate",
      sets: 4,
      reps: parseRepRange("4-8"),
      rest: "120s",
      instructions: "Pausa por 2 segundos no fundo da flexão antes de subir.",
      tips: "Aumenta força isométrica e controle. Técnica avançada.",
      equipment: [],
      calories: 14,
      xpReward: 35,
      estimatedTime: 960,
      category: "control",
      emoji: "⏸️",
    },
    15,
    EXERCISE_THRESHOLDS,
    35,
    960,
    [
      {
        type: "sets",
        exerciseType: "pushup",
        value: 8,
        description: "Complete 8 séries de flexão em anéis",
      },
    ],
    undefined,
    ["Pausa de 2s no fundo", "Corpo reto", "Controle perfeito"],
    ["Comece com pausa curta", "Aumente tempo gradualmente", "Mantenha tensão"],
  ),
  16: createExerciseWithGamification(
    {
      id: "hindi-push-up",
      name: "Flexão Hindu",
      muscleGroup: "chest",
      difficulty: "intermediate",
      sets: 4,
      reps: parseRepRange("4-10"),
      rest: "120s",
      instructions:
        "Do topo, desça para frente, depois para trás, formando um arco.",
      tips: "Movimento fluido que trabalha mobilidade e força. Técnica complexa.",
      equipment: [],
      calories: 16,
      xpReward: 40,
      estimatedTime: 1200,
      category: "mobility",
      emoji: "🕉️",
    },
    16,
    EXERCISE_THRESHOLDS,
    40,
    1200,
    [
      {
        type: "sets",
        exerciseType: "pushup",
        value: 8,
        description: "Complete 8 séries de flexão pausada",
      },
    ],
    undefined,
    ["Movimento fluido", "Corpo em arco", "Controle total"],
    ["Pratique movimento separadamente", "Comece devagar", "Foco na fluidez"],
  ),
  17: createExerciseWithGamification(
    {
      id: "parallel-bar-dips",
      name: "Dips em Barras Paralelas",
      muscleGroup: "chest",
      difficulty: "intermediate",
      sets: 3,
      reps: parseRepRange("4-10"),
      rest: "120s",
      instructions:
        "Apoie-se nas barras paralelas com os braços estendidos. Desça até formar 90° nos cotovelos.",
      tips: "Mantenha o corpo reto e cotovelos próximos. Movimento completo.",
      equipment: ["barras paralelas"],
      calories: 16,
      xpReward: 40,
      estimatedTime: 480,
      category: "strength",
      emoji: "🏗️",
    },
    17,
    EXERCISE_THRESHOLDS,
    40,
    480,
    [
      {
        type: "sets",
        exerciseType: "pushup",
        value: 10,
        description: "Complete 10 séries de flexão hindu",
      },
    ],
    undefined,
    ["Corpo reto", "Cotovelos próximos", "Amplitude completa"],
    ["Comece com poucas reps", "Foco na forma", "Aumente carga gradualmente"],
  ),
  18: createExerciseWithGamification(
    {
      id: "dive-bomber-push-up",
      name: "Flexão Mergulhador",
      muscleGroup: "chest",
      difficulty: "advanced",
      sets: 4,
      reps: parseRepRange("3-6"),
      rest: "150s",
      instructions:
        "Do topo, desça formando um arco, depois suba em movimento contínuo.",
      tips: "Movimento dinâmico que requer coordenação excepcional.",
      equipment: [],
      calories: 18,
      xpReward: 45,
      estimatedTime: 1200,
      category: "explosive",
      emoji: "🚀",
    },
    18,
    EXERCISE_THRESHOLDS,
    45,
    1200,
    [
      {
        type: "sets",
        exerciseType: "pushup",
        value: 10,
        description: "Complete 10 séries de dips em barras",
      },
    ],
    undefined,
    ["Movimento contínuo", "Corpo em arco", "Controle perfeito"],
    [
      "Pratique movimento lento",
      "Aumente velocidade gradualmente",
      "Foco na coordenação",
    ],
  ),
  19: createExerciseWithGamification(
    {
      id: "pseudo-planche-push-up",
      name: "Flexão Pseudo Planche",
      muscleGroup: "chest",
      difficulty: "advanced",
      sets: 4,
      reps: parseRepRange("3-8"),
      rest: "150s",
      instructions:
        "Mantenha os ombros à frente das mãos durante todo o movimento.",
      tips: "Posição avançada que desafia ombros e core. Requer força excepcional.",
      equipment: [],
      calories: 19,
      xpReward: 48,
      estimatedTime: 1440,
      category: "shoulder",
      emoji: "🤸",
    },
    19,
    EXERCISE_THRESHOLDS,
    48,
    1440,
    [
      {
        type: "sets",
        exerciseType: "pushup",
        value: 6,
        description: "Complete 6 séries de flexão mergulhador",
      },
    ],
    undefined,
    ["Ombros à frente das mãos", "Corpo reto", "Core contraído"],
    [
      "Pratique posição estática",
      "Adicione movimento gradual",
      "Construa força lentamente",
    ],
  ),
  20: createExerciseWithGamification(
    {
      id: "depth-push-up",
      name: "Flexão com Profundidade",
      muscleGroup: "chest",
      difficulty: "advanced",
      sets: 4,
      reps: parseRepRange("3-6"),
      rest: "150s",
      instructions:
        "Desça lentamente (3-4s), pausa no fundo, suba explosivamente.",
      tips: "Enfatiza força excêntrica e potência concêntrica.",
      equipment: [],
      calories: 17,
      xpReward: 42,
      estimatedTime: 1440,
      category: "explosive",
      emoji: "📏",
    },
    20,
    EXERCISE_THRESHOLDS,
    42,
    1440,
    [
      {
        type: "sets",
        exerciseType: "pushup",
        value: 8,
        description: "Complete 8 séries de flexão pseudo planche",
      },
    ],
    undefined,
    ["Descida lenta", "Pausa no fundo", "Subida explosiva"],
    ["Comece com pausa curta", "Aumente tempo de descida", "Foco na explosão"],
  ),
};
